##
# This file is part of the @createvibe/proxyobserver project.
#
# (c) Anthony Matarazzo <email@anthonym.us>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.
##

language: node_js

node_js:
    - '14.15.1'

cache:
  directories:
    - node_modules

before_install:
  - npm update

script:
  - npm test